# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42a1c07363af0c9cbcf1d2737f84c96c6275fc8141d67b01a8d864febda141fa6cc62b0b5d3f2d508c3098c69ac04bddaef9255c0e9499a76d28ffd9ace76f32

test:
  secret_key_base: c97dc4c6371c95ea5b58e1fc090d175673104d71d31b1abf75cb04b6184e844e283d1c644871865a32ebf0163fc2a3fa77d89184c0fd1116002506f49a5fa179

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
